spirit-labs/tektite

scripts/run_tests.sh

Without `-f` on Linux (running Fedora),  run_tests.sh throws an error that the files don't exist.

Force remove tmp files when running tests

---

cfg/cluster-minio.conf
cfg/standalone-minio.conf
cfg/standalone.conf

When following the [Getting started](https://tektitedb.com/getting_started/), my local kcat couldn't produce messages and librdkafka spit the error
```shell
bash -c 'while read -r line; do echo "$line" | kcat -b 127.0.0.1:8880 -t my-topic -P -K: ; done'
hello
%3|1717062818.724|FAIL|rdkafka#producer-1| [thrd::8880/0]: :8880/0: Failed to resolve ':8880': Name or service not known (after 1ms in state CONNECT)
% ERROR: Local: Host resolution failure: :8880/0: Failed to resolve ':8880': Name or service not known (after 1ms in state CONNECT)
from%3|1717062819.725|FAIL|rdkafka#producer-1| [thrd::8880/0]: :8880/0: Failed to resolve ':8880': Name or service not known (after 0ms in state CONNECT, 1 identical error(s) suppressed)
% ERROR: Local: Host resolution failure: :8880/0: Failed to resolve …
```

Set loopback ip address in standalone config

---

.github/workflows/ci.yml
integration/bridge_test.go
integration/compaction_test.go
integration/consumer_endpoint_test.go
integration/failover_test.go
integration/levelmanager_test.go
integration/producer_endpoint_test.go
integration/server_test.go
integration/versions_test.go
integration/watermark_test.go
run_tests.sh

This PR is for running the GitHub action on GitHub runner.
Changes:
- Set an `integration` build flag for integration tests.
- Change the GitHub Action workflow to run unit tests followed by integration tests.
Stacked on #93 & #94

Run GitHub action on GitHub runners

---

.github/workflows/cron.yml

After #87 landed, we need to also switch the continuous job to the standard GitHub runner.
- switch the continuous job to the standard GitHub runner.
- Set the job to run twice every hour, I chose a bit of odd minutes (47 & 17) to try and avoid popular times where other colocated jobs would probably run as well.
- Split it into three jobs: build, run-unit-tests, and run-integration-tests (following #96 )

Switch continuous job to standard GitHub runner and split it into three jobs

---

.github/workflows/ci.yml

Currently the CI workflow consists of a single job that's called "build" that does three different kind of validation: build, unit-tests and integration tests. This change will split that into three separate jobs:
- build: it very quickly builds the project without installing any dependency. This is gonna be a fail fast step.
- run-unit-tests: will only run if `build` succeeds
- run-integration-tests: will only run if `build` succeeds and in parallel to run-unit-tests
- Rename the workflow to "Change Validation"
- Split the workflow into three jobs
This way instead of the single "build" item 
we'll have
```mermaid
flowchart LR
A[bulid] --> B(run-unit-tests)
A --> C(run-integration-tests)
```

Split ci workflow into separate jobs

---

opers/aggregate.go
opers/backfill.go
opers/backfill_test.go
opers/bridge_from.go

Just a simple PR to improve some initial buffer sizes when encoding prefixes.

improve initial buffer sizes for encoding key prefixes

---

api/api_test.go
cli/cli_test.go
command/mgr.go
command/mgr_test.go
opers/mgr.go
scripttest/script_test_runner.go
server/server.go
tekclient/client_test.go

This PR:
* Puts back and improved version of the remaining data check at the end of script test, that was removed in an earlier PR.
* Activates command manager after replicators are ready. This ensures we don't fail to process batches at startup, e.g. for saving compacted log state or deleting slabs.

Add remaining data check

---

opers/aggregate.go
opers/mgr.go

Previously, we were using table retentions to delete closed aggregate window state after some time.
Now, we write prefix tombstones to delete the window data once the window is closed which should ensure much more timely deletion.

Delete closed aggregation windows using tombstones

---

levels/compaction_test.go
levels/compaction_worker.go
levels/compaction_worker_test.go
levels/iters.go

This was hard to fix while keeping MaxEntriesIterator, so I've got rid of it and now we gather all results before creating sstables. I think its clearer this way anyway.

fixes bug in compaction where we could miss an entry

---

command/mgr.go
common/sys_table.go
opers/backfill.go
opers/backfill_test.go
opers/bridge_to.go
opers/kafka_in.go
opers/kafka_out.go
opers/mgr.go
opers/offsets.go
opers/partition_hash_cache.go
opers/store_stream.go
opers/store_stream_test.go
scripttest/script_test_runner.go

Previously, we were storing some user related data (offsets for streams, table and backfill operators) under sys tables.
All user data, should be stored under user tables, so they've been moved there, and made sure they're properly deleted on undeploy of streams

Move some user data that was being stored in sys tables to user tables

---

integration/failover_test.go
levels/compaction_test.go
levels/compaction_worker.go
repli/replication.go

If we had same key but with multiple versions at the end of the results of merging sstables and the max table size had not been reached then entries were dropped. This resulted in non deterministic test failures in integration failover tests.
This fixes the bug and adds a couple of explicit tests to cover the case.
The PR also removes an unused method.

Fixes bug in compaction that was causing non deterministic test failures

---

cfg/cluster-minio.conf
cfg/standalone-minio.conf
cfg/standalone.conf
cmd/tektited/main.go
cmd/tektited/runner_test.go
cmd/tektited/testdata/config.hcl
conf/conf.go
conf/conf_test.go
errors/errors.go
integration/bridge_test.go
integration/compaction_test.go
integration/consumer_endpoint_test.go
integration/failover_test.go
integration/kafka_listener_advertised_address_test.go
integration/producer_endpoint_test.go
kafkaserver/api_handler.go
kafkaserver/meta.go
kafkaserver/server.go
kafkaserver/server_test.go
levels/compaction_test.go
objstore/dev/dev_store_test.go
remoting/client_test.go
remoting/connection_test.go
scripttest/script_test_runner.go

This PR introduces a listener config to the Kafka Server configuration which introduces a new `AdvertisedAddresses` config.
>[!Note]
> This is the first of multiple PRs that will introduce the same concept to the HTTP API, web console, and intra cluster.
- Add ListenerConfig abstraction to KafkaServer config.
- Add `AdvertisedAddresses` 
- Add proper validation for `Addresses` and `AdvertisedAddresses` with proper unit tests.
- Refactors the Conf unit tests to use table tests.
- Adds an integration test that validates the broker sending the correct metadata response with broker info when setting `AdvertisedAddresses`
Related to: #81

Add listener config for kafka server listener

---

iteration/merging_iter_bench_test.go

I noticed the benchmark test is broken: keys don't contain the version suffix when added to the iterator.

Fix merging iterator benchmark test

---

command/mgr.go
conf/conf.go
opers/mgr_test.go
proc/processor_test.go
vmgr/vmgr_test.go

Previously it was too high (48), this PR changes it to 12, fixes tests that then broke, and fixed a bug in command manager that was revealed by the change.

Change default number of processors

---

iteration/merging_iter.go
mem/iter.go
mem/memtable_test.go
opers/backfill.go
opers/backfill_test.go
proc/storage.go
proc/storage_test.go

This reduces a lot of complexity. Only place that needs an updatable iterator is backfill, and we create a wrapper iterator for that

Now store iterators are non updatable.

---

iteration/merging_iter.go
mem/iter.go
mem/memtable.go
mem/memtable_test.go
opers/backfill.go
opers/backfill_test.go
proc/storage.go
proc/storage_test.go

Now that memtable.Write() is always called from processor loop, we can simplify the calculation of whether a write can be accommodated by the memtable by not using atomics.
Also, removes an unused method

No need for atomics to ensure memtable is not full

---

command/mgr.go
integration/command_mgr_test.go
levels/compaction.go
levels/compaction_test.go
sst/sstable.go

Now we do not remove tombstones if there are any entries in any tables of the compaction which have a version > last flushed version. This prevents a situation where entries with a tombstone can remain and tombstone can be removed if entry version > last flushed version so not compacted, but tombstone is still removed as last level, resulting in data not being deleted.

Preserve tombstones if any non compactable entries in job

---

iteration/chaining_iter.go
iteration/merging_iter.go
levels/iters.go
mem/iter.go
mem/memtable_test.go
sst/iters.go
sst/sstable_test.go

This PR fixes some bugs introduced after recent major changes to iterators and does some cleanup
* Fixes bug where memtable iterator Current() was returning old entry after Next() had returned valid = false.
* Fixes bug where sstable iterator Current() was returning old entry after Next() had returned valid = false.
* Adds some tests for Current() 
* Merging iterator was removing non compactable entries when key the same
* Make sure iterator.Close() is propagated
* Some cleanup - making return values constants where we know they will be constants, for clarity
@watson28 fyi

Fixes some bugs in iteration

---

debug/debug_on.go
errors/errors.go
integration/failover_test.go
iteration/merging_iter.go
levels/compaction.go
levels/level_manager.go
opers/aggregate.go
opers/aggregate_test.go
opers/mgr.go
opers/window_test.go
opers/windowed_agg_test.go
proc/failure.go
proc/processor.go
proc/storage.go
sanity/sanity_store.go
vmgr/failure.go

This PR fixes a few bugs that were causing intermittent failures in FailoverTests.
* Bug in removing dead version entries which meant the dead version range was removed from the master record while there were still dead entries in the database
* Infinite retry loop for RegisterDeadVersionRange. If this returned wrong cluster version it would end up in an infinite retry loop
* Bug in clearing processor store during failover - wasn't cleared properly resulting in dead versions being visible in queries.
* I have also added a struct called SanityStore - this a device that is useful in detecting whether the store is behaving correctly for puts/gets. After a get in an aggregation we validate it against a get in the SanityStore and make sure the same entry is returned. Bugs with duplicate or …

fixed a few bugs that were causing failover tests to fail

---

asl/api/api_test.go
asl/api/server.go
asl/cli/cli_test.go
client/client_test.go
cmdmgr/mgr.go
integration/command_mgr_test.go
parser/ast.go
parser/ast_test.go
query/mgr.go
query/mgr_test.go

- fixes #4 
- Discussion thread: https://github.com/spirit-labs/tektite/discussions/226
- Local testing
- Created a prepared query `my_query`
- Tried deleting prepared query `my-query` (hypen instead of underscore). As expected this threw an error.
- However, prepared query `my_query` was successfully deleted. 
- Screenshots of all 3 terminals used for local testing:
- terminal-1
- terminal-2
- terminal-3

feat: implement deletion of prepared query

---

iteration/merging_iter_bench_test.go

When creating queries or doing compaction, which uses merging iterators, we would have one iterator per level in the LSM. We'd have 1, 2, 3, 4 or maybe 5 iterators for a very large database.
reference: https://github.com/spirit-labs/tektite/pull/205#issuecomment-2282858969

update merging iterator benchmark with realistic number of iterators

---

.github/workflows/ci.yml

It isn't uncommon for Pull Request to be updated before CI/CD is finished for the previous version. So, we can cancel all old GitHub Actions runs that are stale after a new version of the Pull Request was uploaded.
Reference: https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions

fix: cancel previous github action if new commits are pushed

---

cluster/membership.go
cluster/membership_test.go
kafkaserver/server_test.go

Implements group membership on top of the new distributed state machine. Nodes update their membership periodically by updating an entry for themselves in the shared state along with an updated time. When nodes update they also check the updated time for other nodes, and if the entry is stale the other node's entry is removed. Every time the membership of the group changes, the epoch (an int) is incremented.
This struct is used when all the nodes in a cluster need to agree on which nodes are in the cluster for any particular epoch and which node is the leader.
The PR is based upon the https://github.com/spirit-labs/tektite/pull/241 so you'll see the commit for that one here. I can't set base to be the branch for the other PR or the PR will disappear from this repo, and only appear on my …

Implement cluster group membership

---

lsm/client.go
lsm/compaction.go
lsm/compaction_test.go
lsm/compaction_worker.go
lsm/compaction_worker_test.go
lsm/in_mem.go
lsm/iters.go
lsm/level_manager.go
lsm/level_manager_test.go
lsm/structs.go
lsm/structs_test.go
lsm/table_entries_bench_test.go
lsm/validate.go

This PR extracts and simplifies the level manager into a new lsm.Manager struct.
It includes a more efficient way of representing table entries in memory, whereby the table entries aren't serialized/deserialized when the master record is, but kept in their []byte form. This allows quicker serialization/deserialization and a lower memory footprint. Both of these are important if we're going to be store metadata in S3 on each update.

Extract and simplify level manager into LSM manager

---

cluster/clustered_data.go
cluster/clustered_data_test.go
cluster/membership.go
cluster/membership_test.go
cluster/state_updator.go
cluster/state_updator_test.go
lsm/compaction.go
lsm/compaction_test.go
lsm/compaction_worker_test.go
lsm/level_manager.go
lsm/level_manager_test.go
lsm/structs.go
lsm/structs_test.go
lsm/table_entries_bench_test.go

This PR includes a few things.
* Implements a new struct called ClusteredData which allows a member of the cluster to take safely take ownership of a potentially large piece of data, update it and store it without fear of concurrent updates from another member overwriting changes. It will be used by the controller to store metadata for Tektite, e.g. the LSM metadata.
* Also renames StateMachine to StateUpdator to avoid confusion.
* Some small changes to level manager method names
* Provide a buffer size calculation for master record so we efficiently allocated a buffer of the correct size when serializing.

Implement ClusteredData for ownership and updates of large data. 

---

cluster/clustered_data.go
cluster/state_updator.go
cluster/state_updator_test.go

This patch:
- touches up the docs in Clustered Data to, imo, make the mechanism clearer.
- adds a log prefix and ensures its used consistently in clustered_data
- adds a FetchLatest method to StateUpdator. I thought it's better to abstract that away, as for example - Clustered Data shouldn't really care about the implementation detail of doing a "no-op update" to ensure it fetches the latest state

MINOR: Add a FetchLatest method to StateUpdator and touch up docs a bit

---

go.mod
go.sum
lsm/client.go
lsm/compaction.go
lsm/compaction_test.go
lsm/compaction_worker.go
lsm/compaction_worker_test.go
lsm/in_mem.go
lsm/manager.go
lsm/manager_test.go
lsm/structs.go
lsm/structs_test.go
lsm/validate.go
shard/client.go
shard/manager.go
shard/manager_test.go
shard/rpcs.go
shard/rpcs_test.go
shard/shard.go
shard/shard_test.go
transport/handler_ids.go
transport/local_transport.go

This PR introduces the shard manager and LSM shards.
An LsmShard represents a shard of the LSM. The manager responds to changes in cluster membership and starts and stops shards as appropriate on each agent.
For now, we just have operations: `ApplyChanges` and `QueryTablesInRange` - more will be added as needed.

Shard manager

---

go.sum
objstore/api_test_util.go
shard/client.go
shard/manager.go
shard/manager_test.go
shard/offsets.go
shard/offsets_test.go
shard/rpcs.go
shard/shard.go
shard/shard_test.go
transport/handler_ids.go

This PR implements an offsets cache that lives on the shard controller.
The offsets cache caches next available offset for a topic partition in memory. Before batches of topic data are written to S3, offsets must be obtained and this is where they are obtained from.
The actual offset is stored in the topic data when pushed to S3, and when the shard controller starts it loads the last offset from there.
This PR is based on https://github.com/spirit-labs/tektite/pull/250 so pls only review last commit

Offsets cache

---

logger/log.go
logger/log_test.go

This patch extends log.go to provide prefix-logging functionality, allowing each file/struct/component to define their own logger that'll get prepended to every log message:
```
log, _ := logger.GetLogger("clustered_data.go")
log.Debug("Something happened!")
=> "[clustered_data.go] Something happened!"
```
I hacked around with zap's own benchmark suite and ran the suite 3 times comparing against the usual Zap Sugar logger and this Tektite wrapper. Long-story short:
- for simple messages (like `"Test logging, but use a somewhat realistic message length. (10))`, it's 2x slower - 58 ns/op to 114 ns/op. This is still better than libraries like `apex/log` that do 639 ns/op, `go-kit/kit/log` which does 142 ns/op, `logrus` which does 1129 ns/op and `slog` which does 140 ns/op
- for large …

MINOR: Add configurable logger per package

---

agent/agent.go
agent/conf.go
agent/kafka_api_client.go
agent/kafka_handler.go
agent/produce_test.go
common/util.go
control/client.go
fetcher/client_cache.go
fetcher/fetch_state.go
fetcher/fetcher.go
fetcher/fetcher_test.go
fetcher/local_cache.go
fetcher/local_cache_test.go
fetcher/recent_tables.go
iteration/empty_iter.go
kafkaencoding/encoding.go
kafkaserver2/kafka_server_test.go
levels/compaction_worker.go
lsm/compaction_worker.go
offsets/offsets_test.go
parthash/hash.go
proc/storage.go
pusher/conf.go
pusher/table_pusher.go
pusher/table_pusher_test.go
queryutils/query.go
sst/iters.go
sst/sstable.go
testutils/kafka.go
topicmeta/manager.go

This PR implements BatchFetcher. There is one BatchFetcher for agent, and it is responsible for handling all fetch requests and implementing the entire read path.
For each partition in the fetch request, the fetcher will figure out what table ids contain the required data - this information is either obtained from locally cache info or by querying the controller. 
Once ids are known an iterator can be created, and this iterator will retrieve the actual tables by first looking in a local table cache and then looking in the distributed fetch cache.
As new tables are registered with the controller, the controller will send notifications to all interested agents with the table id and last readable offsets for partitions in that table. On receipt of that information, the BatchFetcher caches …

Implement batch fetcher

---

agent/agent.go
common/util.go
control/client.go
control/client_cache.go
control/controller.go
control/controller_test.go
control/groups.go
control/groups_test.go
control/rpcs.go
control/rpcs_test.go
fetcher/fetcher_test.go
group/coordinator.go
group/coordinator_test.go
group/group.go
pusher/table_pusher.go
pusher/table_pusher_test.go
transport/handler_ids.go
tx/coordinator.go

This PR applies some preparatory work before implementing tx / idempotent producers
* Makes the control/CoordinatorController agnostic to type of key being managed - same logic for managing epochs will be used by both group coordinator and transaction coordinator
* Table pusher now has no knowledge of offsets but allows for direct writes of agnostic KVs - this is used by group coordinator for offset commit and will be used by transaction coordinator for persisting tx state.
* A basic skeleton for the transaction coordinator (unused)

Preparatory work for tx / idempotent producers 

---

agent/list_offsets.go
agent/list_offsets_by_timestamp_test.go
agent/produce_test.go
common/encoding.go
kafkaencoding/encoding.go
pusher/table_pusher.go
pusher/table_pusher_test.go
testutils/kafka.go

The Kafka API allows looking up the first offset from a partition where timestamp >= provided timestamp.
We implement this efficiently in Tekite by periodically storing an index entry for timestamp -> offset for each partition.
Then when looking up we quickly retrieve the last index entry for the timestamp (or the next lowest one), then we scan from there to find the specific offset.

Implement list offsets by timestamp

---

agent/agent.go
agent/conf.go
cluster/clustered_data.go
cluster/membership.go
cluster/state_updater.go
cluster/state_updater_test.go
control/conf.go
control/controller.go
control/lsm_holder.go
control/lsm_holder_test.go
objstore/api.go
objstore/api_test_util.go
objstore/dev/dev_objstore.go
objstore/dev/in_mem.go
objstore/minio/client.go
pusher/table_pusher_test.go

S3 now supports atomic conditional puts by comparing etag. Previously, it only supported conditional updates when the key did not exist at all which forced us into a lot of complexity to ensure atomic updates by creating new keys with a sequence number. That method also created a lot of garbage keys.
Now, we can simply fail to update the key if etag has changed, which simplifies things a lot.

Update state updater and Lsm holder to use conditional put using etag
